### ISSUE TITLE
Request: Auto Start Server

### ISSUE THREAD

**Issue by qwksilver** [intiface/intiface-desktop#64]
It would be nice to have the server mode start just after intiface is launched, perhaps an option in settings?  I don't see one now.  Optionally "intiface.exe -a" type situation to do so if the program is launched from another program, home automation server, or batch file.

**Comment by qdot** [comment]
Great idea! I'm *hoping* to have a new Intiface Desktop version out this week, will see about getting that in.

As for starting things from another program, that's... an interesting question. Basically, Intiface itself is running intiface-cli-(csharp|node, depending on what platform you're on), so you could actually skip intiface desktop altogether in that case if you're interested.

**Comment by qwksilver** [comment]
I might be, but i'm not sure what you mean, and I am currently on windows 10 64bit.

**Comment by qwksilver** [comment]
After a bit of tinkering I've gotten this to work.  I just need to drop it into the automation side, I do still like the autostart idea because I like the desktop interface, and i'm not sure how to run intifacecli in a boxless mode that just keeps going.

**Comment by qdot** [comment]
Yup, I started looking at this last night, and it should be doable. Main holdup right now is that I was planning on also updating electron/vuetify but I may kick that down the road a bit because it's gonna be... difficult.

As for headless, that's actually in the plans. The electron app came out first because I figured more people would want an application, but I've got plans to run Intiface as a web interface using express also, so that you could load it as, say, a Raspberry Pi image and have a dedicated intiface hub. :)

**Comment by qdot** [comment]
This will be in v16 of Intiface Desktop, which should be out in an hour or so. The option is in the "Server Process Settings" portions of the Settings panel, a checkbox at the top of the card.
